version: "2"
services:
  app:
    image: 'openassessmentsclient'
    restart: always
    environment:
      - TERM=xterm
    hostname: 'assessments-clix.tiss.edu'
    build: . 
    volumes:
      - .:/OpenAssessmentsClient
      - /home/core/data/OpenAssessmentsClient/oac:/oac
      - /home/core/data/OpenAssessmentsClient/oat:/oat
    command: >
      /bin/bash -c 'yarn   &&   yarn build   &&   rsync  -avPh  /OpenAssessmentsClient/build/prod/*  /oac/   &&   rsync  -avPh  /OpenAssessmentsClient/build/prod/*  /oat/   &&   mv  -v  /oat/author.html  /oat/index.html'
  web-nginx:
    image: mrunal4/nginx-phusion
    volumes:
      - /home/core/data/nginx-proxy/certs:/etc/ssl/assessments-clix.tiss.edu:ro
      - /home/core/data/OpenAssessmentsClient/oac:/var/www/oac:ro
      - /home/core/data/OpenAssessmentsClient/oat:/var/www/oat:ro      
      - /home/core/new/OpenAssessmentsClient/nginx-conf:/etc/nginx/sites-available
    expose: ["443"]
    environment:
      - VIRTUAL_HOST=assessments-clix.tiss.edu
      - HTTPS_METHOD=noredirect
#      - VIRTUAL_PROTO=https
#      - VIRTUAL_PROT=443
      - LETSENCRYPT_HOST=assessments-clix.tiss.edu
      - LETSENCRYPT_EMAIL=mrunal.nachankar@tiss.edu
    ports:
      - "8180:80"
      - "8143:443"

networks:
  default:
    external:
      name: qbank-oac-oat-bridge-network
